kind: pipeline
name: default

steps:
  - name: rustfmt
    image: rust:latest
    commands:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

  - name: clippy
    image: rust:latest
    commands:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings

  - name: test
    image: rust:latest
    commands:
    - cargo build --verbose --all
    - cargo test --verbose --all

