# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "check-all"

[jobs]

[jobs.check-all]
command = ["cargo", "clippy", "--all-targets", "--color", "always"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true
watch = ["tests"]
