[build]
rustflags = ["-Ctarget-cpu=sandybridge", "-Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3"]

# needed, see https://github.com/RustCrypto/block-ciphers/issues/69
rustdocflags = ["-Ctarget-feature=+aes"]
